---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8090'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.14.1
    ports:
    - 8090:8090
    volumes:
      - ./data/storage:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 10
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'