[tool.poetry]
name = "vector-db-benchmark"
version = "0.1.0"
description = ""
authors = ["Kacper Łukawski <kacper.lukawski@qdrant.com>"]

[tool.poetry.dependencies]
python = "^3.10"
docker = "^5.0.3"
qdrant-client = "0.8.6"
typer = "^0.6.1"
jsons = "^1.6.3"
h5py = "^3.7.0"
weaviate-client = "^3.6.0"
elasticsearch = "^8.3.1"
pymilvus = "^2.1.0"
protobuf = "3.20.0"
redis = "^4.3.4"


[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
