version: '3.5'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: "passwd"
      KIBANA_PASSWORD: "passwd"
      SERVER_SSL_ENABLED: "false"
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  es_data: